# Generated by Django 5.1 on 2024-08-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
