# Generated by Django 5.1 on 2024-08-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='shortInfo',
            field=models.TextField(),
        ),
    ]
